hand_description:
  right_arm:
    hand_frame: sdh_palm_link
    robot_frame: base_link
    attached_objects_name: attached
    attach_link: sdh_palm_link
    hand_group_name: hand
    arm_group_name: arm
    hand_database_name: Schunk
    hand_joints:
      - sdh_knuckle_joint
      - sdh_thumb_2_joint
      - sdh_thumb_3_joint
      - sdh_finger_12_joint
      - sdh_finger_13_joint
      - sdh_finger_22_joint
      - sdh_finger_23_joint
    hand_touch_links:
      - sdh_palm_link
      - sdh_finger_21_link
      - sdh_finger_22_link
      - sdh_finger_23_link
      - sdh_grasp_link
      - sdh_knuckle_link
      - sdh_finger_12_link
      - sdh_finger_13_link
      - sdh_thumb_1_link
      - sdh_thumb_2_link
      - sdh_thumb_3_link
    hand_fingertip_links:
      - sdh_finger_21_link
      - sdh_finger_22_link
      - sdh_finger_23_link
      - sdh_knuckle_link
      - sdh_finger_12_link
      - sdh_finger_13_link
      - sdh_thumb_1_link
      - sdh_thumb_2_link
      - sdh_thumb_3_link
    hand_approach_direction: [0.0,0.0,1.0]
    arm_joints: 
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
